# Generated by Django 5.1.2 on 2024-10-20 22:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quranApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dailyayah',
            name='ayah',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quranApp.ayah'),
        ),
        migrations.AddField(
            model_name='quranedition',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quranApp.language'),
        ),
        migrations.AddField(
            model_name='recitation',
            name='ayah',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quranApp.ayah'),
        ),
        migrations.AddField(
            model_name='reciter',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quranApp.language'),
        ),
        migrations.AddField(
            model_name='recitation',
            name='reciter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quranApp.reciter'),
        ),
        migrations.AddField(
            model_name='recitation',
            name='surah',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quranApp.surah'),
        ),
        migrations.AddField(
            model_name='ayah',
            name='surah',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quranApp.surah'),
        ),
        migrations.AddField(
            model_name='translation',
            name='ayah',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quranApp.ayah'),
        ),
        migrations.AddField(
            model_name='translation',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quranApp.language'),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='preferred_language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quranApp.language'),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='preferred_reciter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quranApp.reciter'),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
