# Generated by Django 5.1.2 on 2024-10-22 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quranApp', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ayah',
            name='english_surah',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quranApp.englishsurah'),
        ),
    ]
