# Generated by Django 5.1.2 on 2024-10-22 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quranApp', '0003_ayah_english_surah'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ayah',
            name='english_surah',
        ),
        migrations.CreateModel(
            name='EnglishAyah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('text', models.TextField()),
                ('text_arabic', models.TextField()),
                ('text_english', models.TextField(blank=True, null=True)),
                ('translations', models.TextField(blank=True, null=True)),
                ('audio_url', models.URLField()),
                ('audio_secondary', models.JSONField(blank=True, null=True)),
                ('english_surah', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quranApp.englishsurah')),
            ],
        ),
    ]
