# Generated by Django 5.1.2 on 2024-10-23 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quranApp', '0004_remove_ayah_english_surah_englishayah'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quranedition',
            name='edition_name',
        ),
        migrations.AddField(
            model_name='quranedition',
            name='author',
            field=models.CharField(default=True, max_length=255),
        ),
        migrations.AddField(
            model_name='quranedition',
            name='name',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='quranedition',
            name='url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='quranedition',
            name='language',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
